### ISSUE TITLE
start

### ISSUE THREAD

**Issue by Abdumagnate** [Abdumagnate/Barkamolavlod.uz#1]
guys read about how to create a website. tomorrow we will talk and do.

**Comment by Abdumagnate** [comment]
j

**Comment by PrinceEntertainment** [comment]
Sayt  o'zimizgami  yo'ki  TBM gami ?

**Comment by PrinceEntertainment** [comment]
Front END  saytti  yasabermadimi

**Comment by Abdumagnate** [comment]
boshqalaga

**Comment by Abdumagnate** [comment]
ozimiz uchun

**Comment by Abdumagnate** [comment]
poleznio

**Comment by Abdumagnate** [comment]
welcome

**Comment by Fatxullayev** [comment]
GOT IT

**Comment by Abdumagnate** [comment]
if u presss ctr+enter  u will commit

**Comment by Abdumagnate** [comment]
hotkey

**Comment by Abdumagnate** [comment]
shortcut

**Comment by Fatxullayev** [comment]
COMMIT hotkey?

**Comment by Abdumagnate** [comment]
no

**Comment by Abdumagnate** [comment]
and then press ctrl+enter ull see

**Comment by Abdumagnate** [comment]
text a cooment

**Comment by Fatxullayev** [comment]
ok

**Comment by Fatxullayev** [comment]
I was just confused cuz u said commit ;)

**Comment by Fatxullayev** [comment]
https://www.dtelepathy.com/blog/inspiration/learn-a-thing-or-two-30-education-sites-done-right

**Comment by Fatxullayev** [comment]
check that out

**Comment by Fatxullayev** [comment]
Prior to creating a site, you must ascertain what your audience wants and expects in terms of content,
design, and how the site will work (by way of talking to the relevant people, and also, if your budget allows,
by using surveys and focus groups). You don’t have to take all of your audience’s ideas into account (after
all, many will be contradictory), but be mindful of common themes and ensure they’re not ignored.

**Comment by Fatxullayev** [comment]
hey, yaxshi g'oya
bizda manimcha hali yoshlar uchun maxsus sayt yaratilmagan

**Comment by Fatxullayev** [comment]
bekorchilik qilmasdan bolalar nimadir o'rganishsadi internetdan, foydali narsalar olishadi
ko'rinishi bollar uchun bo;lish  kerak?

**Comment by Fatxullayev** [comment]
How to send files? And, I think We should take photos one more time with perfect views

**Comment by Fatxullayev** [comment]
are you reading this

**Comment by Fatxullayev** [comment]
give 10 purposes of oour site!

**Comment by Fatxullayev** [comment]
then we will discuss about view, and then we will collect material.

**Comment by Abdumagnate** [comment]
jsut d o  it

**Comment by Fatxullayev** [comment]
what should do then anything

**Comment by Fatxullayev** [comment]
whatever

**Comment by Abdumagnate** [comment]
dont be tupid study programming

**Comment by Fatxullayev** [comment]
https://www.thespruce.com/best-free-educational-websites-for-kids-3129084

**Comment by Abdumagnate** [comment]
read it

**Comment by Fatxullayev** [comment]
what

**Comment by Abdumagnate** [comment]
https://wordpress.com/stats/day/avlod.wordpress.com

**Comment by Fatxullayev** [comment]
fatkhullaev97@gmail.com

**Comment by Fatxullayev** [comment]
https://www.youtube.com/watch?v=M4htgnXZYcw

**Comment by Abdumagnate** [comment]
file:///C:/jAVA/BARKAMOL/0.html

**Comment by Abdumagnate** [comment]
![image](https://user-images.githubusercontent.com/34268237/34455721-d761f9f4-eda6-11e7-919b-67b96ee23637.png)
guys learn https://www.w3schools.com/bootstrap4/default.asp
